### ISSUE TITLE
Proposed RFC Feature: Asset Reference Improvements

### ISSUE THREAD

**Issue by junbo75** [o3de/sig-content#103]
### Summary:
Assets in O3DE often refer to other assets, for loading, processing, dependencies, and more. There are many ways to reference one asset from another, including by asset ID (a universally unique identifier) and by filename/path. The way assets refer to other assets differs from system to system and can have a large impact in what the system can do with those references: For example, specifying just the filename of a final product asset can make it impossible for the system to escalate the processing order of the source asset that will emit the referenced product asset. Specifying the product asset ID can remedy this on-demand processing problem potentially, but the product asset ID is confusing and opaque to most users. As a product asset can be produced from a series of [intermediate assets](https://www.o3de.org/docs/user-guide/assets/pipeline/intermediate-assets/) and its asset ID only contains the identifier of the last intermediate asset on the chain, asset ID based reference may also be insufficient to trace up the original source asset for supporting on-demand processing.

This RFC attempts to improve the asset references in O3DE by proposing:
- A new alias system for referencing source assets via human readable aliases for improving the readability.
- New source/product asset reference data structures that are flexible enough to accept different types of asset references.
- Adding processing chain information into the product asset reference structures, to support tracing the processing chain from the referenced product asset to its original source asset.

### What is the relevance of this feature?
Before digging into the relevancy of this RFC, it's important to understand why we cannot fix these issues with just asset ID changes. Some O3DE developers prefer to use filename or path based references since referencing assets by their asset IDs are relatively hard:
- Filename/path is much more human readable than the asset ID, which makes it more aligned with how early development works and how certain systems are built. For example. PopCornFx requires to load its foundational asset (i.e. DistortionPass) via filename/path.
- For source assets created from 3rd party content tools, the translation between asset IDs and filenames/paths is not ideal and sometimes not possible for workflows like debugging in Python, Lua or C++, since asset IDs are only available after the source assets are processed by the Asset Processor and 3rd party content tools may not have access to the O3DE asset database as well.
- Systems are not designed for supporting asset relocation or scoped/on-demand processing. For example:
    - Source/product assets can be treated as code or code dependencies in Shader languages.
    - Some systems predate the current Asset Pipeline and continue to use direct file asset loading.
    - The system framework requires file name/path based references for using string manipulation, wild cards, regular expressions for locating or selecting assets.
- The asset ID have not been created yet and are not predictable when referenced by another source asset. An example is that the Prefab Group (AKA procedural prefab) stores file hints (relative path) to assets before the product assets are created.

Intermediate assets introduce a secondary referencing problem for O3DE: The Asset Processor may not know what source asset to process based on the limited source asset information included in the product asset ID. Suppose that users have no product assets produced via the Asset Processor yet and there's a processing chain like below:
![Example Processing Chain](https://user-images.githubusercontent.com/68558268/209860452-c0d7aa69-0700-4003-af7d-f47950a519bf.png)
If a level only references the cube.azmodel using the current asset system, the Asset Processor wouldn't know that it needs to start by processing shape_procedural.houdini as there is no clue for it to use to discover that.

The proposed solution address the pain points users run into when working with asset IDs, while keeping the flexibility of supporting different types of asset reference:
- The alias system improves the readability of asset references. Instead of using the opaque asset ID, developers can reference the source asset as well its product assets via the semantic meaningful aliases.
- The proposed asset reference data structures make sure that O3DE can handle multiple asset references types (asset ID, alias or file name/path) required by the O3DE or external systems. It helps to minimize people's effort to migrate to the suggested reference type to support impactful asset pipeline features like the [asset relocation](https://github.com/o3de/sig-content/issues/77) and [asset bundling](https://www.o3de.org/docs/user-guide/packaging/asset-bundler/).
- The processing chain is baked in the asset reference, which can be used to build the asset processing graph. Product assets can be mapped back to their source assets for supporting scoped/on-demand asset processing.

#### Terminology
- [Source asset](https://www.o3de.org/docs/user-guide/assets/pipeline/source-assets/) - Files that contain unprocessed data that you want to consume in Open 3D Engine (O3DE) Editor or Launcher. Source assets can include: models, textures, animations, audio files and other content, typically authored in digital content creation (DCC) tools.
- Product asset - The output of a series of Asset Pipeline steps to convert a source asset to its runtime optimized form for use in O3DE. For example, the source asset might be a FBX but the pipeline crunches, optimizes and converts it into an AtomMesh product asset. The engine loads the product asset only, not the original FBX.
- [Intermediate asset](https://www.o3de.org/docs/user-guide/assets/pipeline/intermediate-assets/) - Intermediate files that allow builders to be chained together and add discrete steps for asset processing which increase builder reusability.
- Source GUID - A source GUID is used to identify assets. It is generated by hashing the path-relative to the scan folder-of the source asset file. It is technically a UUID value, but is commonly referred to as a GUID.
- Sub ID - Sub Index of a product asset which distinguish it from other product assets produced from the same source asset. Sub IDs are usually generated by an asset builder. They must be stable for running in a build, and mutually exclusive. 
- Asset ID  - The asset ID consists of the source UUID plus a sub ID, which uniquely identifies a product.
- Processing chain - One source asset can undergo several Intermediate steps before finally becoming a product that is usable by the engine. Sometimes these intermediates are processed into multiple different product assets or used by the engine directly, in addition to the final product being used by the engine (for example, plain text of shaders, emitted as an intermediate during compilation of a final binary shader is at the same time a source asset (an input to the next step of the pipeline) as well as a product (it can be loaded directly to use for debugging information).
- Source/Product asset reference - The reference to a specific source/product asset in another source asset or code. Currently product assets can only be referenced via its asset ID or filename/path.
- Source asset alias - Alias of a specific source asset that can be used to reference it in code or other assets. For example, users may define an alias called "Procedural Shapes Procgen File" for the source asset "shape_procedural.houdini". Note that source asset aliases can also be included in the product asset references: Assume that the source asset "shape_procedural.houdini" produces a product asset called "Shapes.fbx". Then "Shapes.fbx" can be referenced as "Procedural Shapes Procgen File : 0", where "Procedural Shapes Procgen File" represents the source asset and 0 is the product sub ID.

#### High level design
- Add human readable aliases for source assets:
    - Save the source asset aliases to the asset metadata file (Check [RFC - Metadata Asset Relocation](https://github.com/o3de/sig-content/issues/77) for the metadata file generation).
    - Update the asset database tables to store the alias information.
    - Allow users to define asset dependencies via source aliases.
    - Add GUI tools in the Asset Processor for managing aliases of each source asset.
- Add two new data structures (ProductReference and SourceReference) for serializing/deserializing different types of source/product asset references:
    - ProductReference has implicit conversion to the asset ID while the SourceReference has implicit conversion to the source asset ID underneath.
    - File name/path based references (const char*) from 3rd party tools can always be wrapped into ProductReference and SourceReference since the new structures are flexible enough to accept several different formats of asset references.
- Record processing chain information inside the new SourceReference and ProductReference structures: 
    - The new structures will include a string type field which stores the processing chain. This field will be serialized to disk and deserialized for on-demand/scoped processing when loading the asset.
    - The maximum number of chain steps written to the processing chain will be configurable via an CMake parameter, but the original source asset and the last intermediate asset before the final product asset should always be included in the processing chain.

#### Example
Suppose users have the following processing chain: shape_procedural.houdini (original source asset) → Shapes.fbx (intermediate asset) → cube.azmodel (final product asset):
- Source GUID of shape_procedural.houdini is {68458F51DA535183B342E7C9415026C3}
- Source GUID of Shapes.fbx is {1AC5928D0E605032A79D58E828B1981C}
- Product asset ID of cube.azmodel is {1AC5928D0E605032A79D58E828B1981C} : 0

Assume we have a component class that holds a reference to a model like below:
```
class MyComponentClass : AZ::Component
{
    ...
public:
    ...
    Asset<AzmodelType> m_MyModel; // Reference to cube.azmodel and also loads the asset data during deserialization 
    void OnTick()
    {
        ... // Operations on m_MyModel
    }  
 
   static void reflect(...) // reflects m_MyModel
}
```

##### Before this proposal

If the above class is on an entity in the level (which is a prefab), its data will be serialized like this in the actual file stored on disk.
```
Using asset ID:

"MyComponentClass": {
    "m_MyModel": {
         "assetId": {
            "guid": "{1AC5928D-0E60-5032-A79D-58E828B1981C}",
            "subId": 0
          },
          "assetHint": "cube.azmodel",
     }
}

Or using file path:

"MyComponentClass": {
    "m_MyModel": {
         "assetPath": "cube.azmodel",
     }
}
```

If developers want to load cube.azmodel by its file path using the asset system API like [GetAsset()](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetManager.h#L214), they will have to do the conversion from file name/path based references to the asset ID based references explicitly:
```
Data::AssetId cubeAssetId;
Data::AssetCatalogRequestBus::BroadcastResult(
    cubeAssetId,
    &Data::AssetCatalogRequestBus::Events::GetAssetIdByPath,
    "cube.azmodel",
    azrtti_typeid<AzmodelType>(),
    false);

auto cubeAsset = Data::AssetManager::Instance().GetAsset<AzmodelType>(cubeAssetId, AZ::Data::AssetLoadBehavior::PreLoad);
```

##### After this proposal
With the proposed solution and the metadata file introduced by [RFC - Metadata Asset Relocation](https://github.com/o3de/sig-content/issues/77), the source asset shape_procedural.houdini should have a metadata file side by side with the following content:
```
{
    "UUID": {
        "uuid": "{68458F51-DA53-5183-B342-E7C9415026C3}",
        "legacyUuid": "{11111111-2222-3333-4444-555555555555}"
    },
    "Aliases" : [
        "scan_directory.shape_procedural.houdini"
    ]
}
```

Similarly, the intermediate Shapes.fbx can also get a metadata file defined as:
```
{
    "UUID": {
        "uuid": "{1AC5928D-0E60-5032-A79D-58E828B1981C}",
        "legacyUuid": "{22222222-3333-4444-5555-666666666666}"
    },
    "Aliases" : [
        "intermediate_asset_directory.Shapes.fbx"
    ]
}
```

MyComponentClass will still include the Asset<AzmodelType> type member, m_MyModel, but m_MyModel will keep a reference to the cube.azmodel using the new productReference type instead of the asset ID.
```
Using asset ID:

"MyComponentClass": {
    "m_MyModel": {
         "productReference": {
             "id": "{1AC5928D-0E60-5032-A79D-58E828B1981C}:0",
             "processingChain": "{68458F51-DA53-5183-B342-E7C9415026C3}"
          },
          "assetHint": "cube.azmodel"         
     }
}

Or using alias:

"MyComponentClass": {
    "m_MyModel": {
        "productReference": {
            "id": "intermediate_asset_directory.Shapes.fbx:0",
            "processingChain": "scan_directory.shape_procedural.houdini"
         },
         "assetHint": "cube.azmodel"
     }
}

Or using processing chain:

"MyComponentClass": {
    "m_MyModel": {
        "productReference": {
            "id": "scan_directory.shape_procedural.houdini:intermediate_asset_directory.Shapes.fbx:0",
            "processingChain": ""
         },
         "assetHint": "cube.azmodel"
     }
}

Or using file path:

"MyComponentClass": {
    "m_MyModel": {          
        "productReference": {
            "id": "cube.azmodel",
            "processingChain": "scan_directory.shape_procedural.houdini"
         },
         "assetHint": "cube.azmodel"
}
```

Similar asset reference updates will apply to the legacy ObjectStream format asset like uicanvas as well.

To call the same asset system API like [GetAsset()](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetManager.h#L214), developers can pass any type of references to it directly:
```
Using asset ID:

auto cubeAsset = Data::AssetManager::Instance().GetAsset<AzmodelType>(
    ProductReference("1AC5928D-0E60-5032-A79D-58E828B1981C:0", "68458F51-DA53-5183-B342-E7C9415026C3"),
    AZ::Data::AssetLoadBehavior::PreLoad);

Or using alias:

auto cubeAsset = Data::AssetManager::Instance().GetAsset<AzmodelType>(
    ProductReference("Shapes.fbx:0", "scan_directory.shape_procedural.houdini"),
    AZ::Data::AssetLoadBehavior::PreLoad);

Or using processing chain:

auto cubeAsset = Data::AssetManager::Instance().GetAsset<AzmodelType>(
    ProductReference("scan_directory.shape_procedural.houdini:intermediate_asset_directory.Shapes.fbx:0", ""),
    AZ::Data::AssetLoadBehavior::PreLoad);

Or using file path:

auto cubeAsset = Data::AssetManager::Instance().GetAsset<AzmodelType>(
    ProductReference("cube.azmodel", "scan_directory.shape_procedural.houdini"),
    AZ::Data::AssetLoadBehavior::PreLoad);
```

Combining with the [RFC - Product Sub ID Type Update](https://github.com/o3de/sig-content/issues/93), cube.azmodel can even be referenced via "scan_directory.shape_procedural.houdini:intermediate_asset_directory.Shapes.fbx:cube.azmodel", which makes the reference more readable and predictable. However, it's not recommended to use the source asset path as its alias since the alias would become confusing when the source asset is relocated. Asset ID will be safer to use since relocating an asset will not change the asset ID any longer (Check [RFC - Metadata Asset Relocation](https://github.com/o3de/sig-content/issues/77) for more details).

#### Alias system
The proposed alias system is based on the indirection layer for source assets proposed in [RFC - Metadata Asset Relocation](https://github.com/o3de/sig-content/issues/77).

##### Create alias for source asset
When the Asset Processor create the metadata file for each new source asset, a new array field called "Aliases" will be added to the file and a default alias "{Scan Directory Name}.{Source Asset Name}.{Source Asset Extension}" will be defined:
```
{
    "UUID": {
        ...
    },
    "Aliases" : [
        "{Scan Directory Name}.{Source Asset Name}.{Source Asset Extension}"]
}
```
For source assets with the exact same file name and extension but under different directories, an incremental number will be suffixed to the default alias (e.g. {Scan Directory Name}.{Source Asset Name}_1.{Source Asset Extension}). Developers can also define custom aliases for separating these files via the provided UI interface in the Asset Processor. The Asset Processor will keep a map from the file alias to the actual file UUID and prevent developers from assigning the same alias to different source assets. Error messages should be thrown in this case with suggestions to rename the alias. 

File aliases are expected to write to a new asset database table "SourceAliases" by the Asset Processor with the following fields:
| Field Name | Description                                                                                                                            |
| -----------   | ------------------------------------------------------------------------------------------------- |
| AliasID        | A incremental number that identify an alias in the table                                                      |
| SourcePK    | SourceID from the "Sources" table which identify an existing source asset entry uniquely |
| Alias           | Name of the alias                                                                                                                   |

The metadata file is monitored by the Asset Processor's asset scanner. When a new alias is added to it, the Asset Processor will add new entries to the "SourceAliases" table accordingly **without** reprocessing the source asset.

Source alias information will also be written to the asset catalog for resolving the aliases when users run the released O3DE applications that don't have access to the asset database. For example, the Asset Builder may just copy specific type of source assets into the cache directly without any processing. Alias information has to be included the asset catalog in this case for resolving these aliases at runtime. Another example is that users can write a Lua script or a C++ file with permissive asset references with source aliases that will not be resolved during the asset processing. Currently the asset catalog includes a map from product filenames to asset IDs. The map will be extended to support asset references with aliases besides filenames for locating the referenced product assets at runtime.

Aliases will be treated the same as the source GUIDs that the Asset Builder may also use to declare source/product dependencies and be written to the source/product dependencies table inside the asset database.

##### Manage aliases
New tools will be provided in the Asset Processor GUI for people to add, modify or remove aliases for each source asset. The Asset Processor Batch will also be updated for CLI support on managing aliases.
![image](https://user-images.githubusercontent.com/68558268/209862371-cccb9390-49ae-4354-90a5-a16a8d0a2a78.png)

Whenever people needs to modify or delete an existing alias, the Asset Processor will query the source/product dependencies tables to check whether alias is still in use. Alias should only be modified or deleted when it's not referenced in any source assets to prevent breaking existing asset references. As an future extension, the Asset Processor may scan any specified directory (e.g. project folder) and aids people to replace all the outdated alias if they're willing to do so.
![image](https://user-images.githubusercontent.com/68558268/209862417-fb4d0bfc-ef2e-45bb-b61b-23c01696a994.png)

##### Data structure
Two new data structures (ProductReference and SourceReference) will be defined at the AzCore level which accept different types of references and convert any reference to the source GUID/asset ID underneath implicitly. The structures will also store the processing chain information for scoped/on-demand processing.
```
static constexpr size_t MaxProcessingChainStringBuffer = (AZ::Uuid::MaxStringBuffer + 1) * MaxProcessingChainSteps - 1; /// Chain of UUIDs size (includes terminal and ":")
using FixedProcessingChainString = AZStd::fixed_string<MaxProcessingChainStringBuffer>;

struct ProductReference
{
    AZ_TYPE_INFO(ProductReference, "{0955D9FA-7CAA-4E06-99FB-EF56A4FA72D6}");
	
    //! Create an asset reference from the provided asset ID.
    ProductReference(AZ::Data::AssetId assetId, AZ::Data::FixedProcessingChainString processingChain = "");
    //! Create an asset reference from the provided string (asset ID string with/without alias, relative path or processing chain).
    ProductReference(AZStd::string_view stringId, AZ::Data::FixedProcessingChainString processingChain = "");
    
    //! Whether the provided reference string can be resolved to an actual asset ID.
    bool IsValid() const;

    //! Reflect to serialize context and behavior context.
    static void Reflect(ReflectContext* context);
    
    //! Convert to an asset reference string.
    template<class StringType>
    StringType ToString() const;

    //! Resolve to the actual asset ID.
    AZ::Data::AssetId ToAssetId() const;

	AZStd::string m_id;                                     // Product identifier in the string type (asset ID, alias, file path or processing chain)
    AZ::Data::FixedProcessingChainString m_processingChain; // Processing chain of the product asset
};

struct SourceReference
{
    AZ_TYPE_INFO(SourceReference, "{A8FC68B2-9FFE-4944-ACFF-5992493CF3F4}");
    
    //! Create an asset reference from the provided source asset ID (UUID).
    SourceReference(AZ::Uuid sourceGuid, AZ::Data::FixedProcessingChainString processingChain = "");
    //! Create an asset reference from the provided string (source UUID string, source alias or relative path).
    SourceReference(AZStd::string_view stringId, AZ::Data::FixedProcessingChainString processingChain = "");
    
    //! Whether the provided reference string can be resolved to an actual source asset ID (UUID).
    bool IsValid() const;

    //! Reflect to serialize context and behavior context.
    static void Reflect(ReflectContext* context);
    
    //! Convert to a source asset reference string.
    AZStd::string ToString() const;

    //! Resolve to the actual source asset ID (UUID).
    AZ::Uuid ToSourceGuid() const;

	AZStd::string m_id;                                     // Source identifier in the string type (source GUID, alias, file path or processing chain)         
    AZ::Data::FixedProcessingChainString m_processingChain; // Processing chain of the source (The source could be an intermediate)
};
```

Any existing components that include the [Asset<T>](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L294) or the [AssetData](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L112) type members will keep unchanged for backward compatibility while the asset ID stored inside [Asset<T>](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L294) and [AssetData](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L112) class will be replaced with the new ProductReference type.
```
Before:
template<class T>
class AssetData
{
public:
    ...
    AssetData(const AssetId& assetId = AssetId(), AssetStatus status = AssetStatus::NotLoaded)
        : m_status(status)
        , m_assetId(assetId)
    {}
    ...
protected:
    ...
    AssetId m_assetId;
    ...
}

template<class T>
class Asset
{
public:
    ...
    Asset(const AZ::Data::AssetId& id, AssetData* assetData, AssetLoadBehavior loadBehavior);
    Asset(const AZ::Data::AssetId& id, const AZ::Data::AssetType& type, const AZStd::string& hint = AZStd::string());
    ...
protected:
    ...
    AssetId m_assetId;
    ...
}

After:
template<class T>
class AssetData
{
public:
    ...
    AssetData(const ProductReference& assetReference = ProductReference(), AssetStatus status = AssetStatus::NotLoaded)
        : m_status(status)
        , m_assetReference(assetReference)
    {}
    ...
protected:
    ...
    ProductReference m_assetReference;
    ...
}

template<class T>
class Asset
{
public:
    ...
    Asset(const ProductReference& assetReference, AssetData* assetData, AssetLoadBehavior loadBehavior);
    Asset(const ProductReference& assetReference, const AZ::Data::AssetType& type, const AZStd::string& hint = AZStd::string());
    ...
protected:
    ...
    ProductReference m_assetReference;
    ...
}
```
Similarly, any existing asset system APIs that accept a file name/path or [Asset ID](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L55)/UUID based reference will be updated to accept the ProductReference/SourceReference type. For example,
```
Before:
template<class AssetClass>
Asset<AssetClass> GetAsset(const AssetId& assetId, AssetLoadBehavior assetReferenceLoadBehavior, const AssetLoadParameters& loadParams = AssetLoadParameters{});

After:
template<class AssetClass>
Asset<AssetClass> GetAsset(const ProductReference& assetReference, AssetLoadBehavior assetReferenceLoadBehavior, const AssetLoadParameters& loadParams = AssetLoadParameters{});
```

Any assetId or string type value passed to the old APIs can be converted to the ProductReference/SourceReference type implicitly, so that no changes are required for calling these asset APIs in the existing code base.

##### Asset system APIs
New APIs will be added at the AzCore level to resolve asset references to asset ID and to retrieve the processing chain from asset references:
```
class AssetReferenceRequests
{
public:
     AZ_RTTI(AssetReferenceRequests, "{B02EF51A-49CD-4035-A120-CDB5CD7680B1}");

     //! Resolve different type of product asset references (e.g. asset ID with source aliases, processing chain. etc.) to the asset ID.
    virtual AZ::Data::AssetId GetAssetIdByProductReference(ProductReference /*productReference*/) = 0; 

     //! Resolve different type of source asset references (e.g. source aliases, processing chain. etc.) to the source GUID.
    virtual AZ::Uuid GetSourceGuidBySourceReference(const char* /*alias*/) = 0;
    
    //! Retrieve the processing chain string based on the provided product asset reference
    virtual AZ::Data::FixedProcessingChainString GetProcessingChainByProductReference(ProductReference /*productReference*/) = 0;
    
    //!  Retrieve the processing chain string based on the provided source asset reference
    virtual AZ::Data::FixedProcessingChainString GetProcessingChainBySourceReference(SourceReference /*sourceReference*/) = 0;
}
```
At the AzFramework level, AssetCatalog will handle the requests to resolve source/product asset references by querying its internal maps from filenames or aliases to the asset ID. While at the AzToolsFramework level, a request handler will be implemented to query the actual asset database. If the processing chain field included in the ProductReference/SourceReference is empty, the request handlers will follow the orders below to construct the value:
1. If the asset database exists, query the asset via its asset ID/GUID or path to construct the processing chain.
2. Otherwise treat the source GUID included in the asset ID as the original source asset to construct the processing chain.

##### Serialization/Deserialization
The [AssetSerializer](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetSerializer.h) and [AssetJsonSerializer](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetJsonSerializer.h) will be updated to convert the old asset references to the new type when serialize source assets again. Processing chain will be also constructed automatically via the proposed asset system APIs and saved to disk when the processing chain field inside the ProductReference/SourceReference structure is empty, so that the chain information will be available for supporting scoped/on-demand asset processing.

### What are the advantages of the feature?
- Easily track the processing chain of an asset via its asset reference, which helps to unblock the high impact asset pipeline improvements like on-demand/scoped asset processing.
- Customers who are working with hand-edited/hand-written files (e.g. shader files) will be able to reference assets via file alias instead of using the opaque asset ID.
    - Quotes from game developers: "Later, we moved to Human readable string IDs (id1: Tank, Id2: turret) ... life was so much better.  We captured all the IDs during build time as they were created, and we could flag when there were conflicts.  But the benefit was easier intuitive scripting, and much easier debugging."
- The alias system makes asset references more human readable and predictable without querying the asset database or check the Asset Processor GUI. People can even reference an asset that hasn't been processed yet following the alias patterns. 
- The flexible asset reference structures allow people to reference assets using any type they prefer without doing the conversion explicitly, which makes it easier to migrate to the asset ID based references if people want to get the asset relocation and on-demand asset processing supports. Wrapping and centralizing the conversions between different reference types in the new data structure helps to reduce the effort for editing each explicit conversions in the code base when the conversion logic changes (e.g. source UUID isn't calculated based on the file relative path any more) as well.
- The flexible asset reference structures work well with the string type asset references coming from 3rd party tools.

### What are the disadvantages of the feature?
- Any updates in the asset processing chain may break the existing processing chain hint stored in the asset references and effects the on-demand/scoped processing.
- Source asset aliases may become less meaningful after the corresponding source assets are relocated and modifying/deleting an existing alias can easily break existing references in source assets or code.
- The metadata file is checked into source control and shared by every developer. One developer could potentially break other's work when modify/delete an alias even though the alias is not in use on the developer's local machine, since the old alias may still referenced by someone else's local changes.
- The alias system complicates the existing asset processing pipeline and system. Source GUID/asset ID will be more discoverable once it's included in the metadata file and the alias system can be delayed unless there're strong use cases/requirements for it. 
- The flexible asset reference structures may cause people rely more on the file name/path based references if they still find the asset ID hard to use in their workflow.

### How will this be implemented or integrated into the O3DE environment?
- The existing serialized asset references will be converted to the new format once they're serialized again.
- The alias system is a new feature for referencing assets via human readable aliases and no migration is needed.

### Are there any alternatives to this feature?
- Bake the processing chain into the asset ID which will be stored in the asset database and runtime catalog.
    - The existing source GUID/asset ID is enough for identifying a source/product asset
    - The information from the asset database is sufficient to construct the full processing chain if developers need. Writing the processing chain into the asset database just duplicates the existing data.
    - The processing chain is only useful for scoped/on-demand processing. Developers don't need it when they bundle their application assets for final release since all the assets should have already been generated at that point.
- Deprecate the asset APIs for resolving a file name/path to its asset ID and force people to switch to the asset ID based references in O3DE.
    - O3DE has no control over files managed by a 3rd party vendor and those files may reference other assets via their own formats.
    - Some source assets (like shaders) make reference other assets as code dependencies via file paths and don't expect to process the referenced assets to be relocated or processed on demand.
    - The existing asset ID format still not provide sufficient information to trace up the original source asset if intermediates are involved.
- To trace up the source asset information from the asset file name/path, retrieve the asset catalog from a remote location (e.g. [asset cache server](https://www.o3de.org/docs/user-guide/assets/asset-processor/asset-cache-server/)) to resolve the file name/path.
    - This requires developers to set up additional asset pipeline features and could bring up their cost by hosting remote server(s). The cached asset database/catalog data may also be out of date and cause lookup failures. This solution also requires significant effort and will be time consuming, so it is not a short term solution.
    - This solution cannot resolve the broken reference issue when the asset is relocated.
- To trace up the source asset information from the asset file name/path, update the asset processing pipeline to have create jobs emit stub product assets or just the names of product assets that might get generated, or a new step between create and process jobs.
    - For many graphics file types such as FBX, Houdini and others, discovering what they contain and executing the various heuristics that determine what the outputs for it would be would cost as much in terms of processing time and computation as just processing it would, so pre-determine all outputs for all jobs up front before doing any jobs is not ideal for tracing the processing chain.
    - This solution cannot resolve the broken reference issue when the asset is relocated.
- To trace up the source asset information from the asset file name/path, use some sort of heuristics to guess what the source might be based on the product asset file name/path.
    - We do already use a heuristic that widens the net, but it still fails in some cases like "shapes.fbx → cube.mesh".

### How will users learn this feature?
- Impactful change notification will be sent to the discord channel and included in the O3DE release notes.
- Public O3DE document will be created for the new alias system and asset reference structures.

### Are there any open questions?
- What's the list of assets that don't need to be relocatable and are expected to be fixed manually after relocation?
    - One concern is that the people who chose the path references weren't the same people who relocated the files, and there was a pretty long gap (over a year?) between adding the references and someone moving them.
- What's the guideline for developers to define file aliases that are still meaningful after relocation to avoid unnecessary modifications? Should O3DE define default alias for each source asset?
- What other improvements can we made around asset ID to make it more discoverable and readable to address people's pain points in working with asset ID based references? 
    - For example: Allow people to drag & drop or copy & paste assets from the Asset Processor/Browser when work in O3DE content tools, so that people don't need to work with asset IDs directly.
- Can we remove UUIDs from the asset system and only use the proposed alias system for asset IDs?

**Comment by tonybalandiuk** [comment]
>>The existing serialized asset references will be converted to the new format once they're serialized again.
>>The alias system is a new feature for referencing assets via human readable aliases and no migration is needed.
@junbo75 
I am thinking about the situation where a developer is using O3DE today and maybe late in their project, and maybe they don't want to upgrade to a new system because they are naturally conservative about introducing any changes.

1) Once this is implemented, is the upgrade to using the new asset system and file format a one-way door?  If something goes wrong, is there a way to roll back and use the old system?
2) Will this be implemented with a feature flag?

**Comment by junbo75** [comment]
Hi @tonybalandiuk,
1. The alias system is completely new and is optional for people to use. The updated asset system APIs will be backward compatible, so that the existing systems can still pass the their current references to the APIs without requiring any functional changes. For existing components that keep the Asset<T> type pointers, the reference will be updated to use the new asset reference structures during serialization automatically, which could be a potential risk for developers who don't want to introduce any changes to the engine or their project. 
2. Yeah, I think that's a good callout. We should consider adding a feature flag which decides the format we serialize asset references to disk. People can get the option to continue using their current asset reference format if they prefer.

**Comment by allisaurus** [comment]
Curious about this situation:

> * Any updates in the asset processing chain may break the existing processing chain hint stored in the asset references and effects the on-demand/scoped processing.

What happens in this scenario, does the asset get reprocessed from scratch and updated with a new processing chain hint?

**Comment by junbo75** [comment]
> Curious about this situation:
> 
> > * Any updates in the asset processing chain may break the existing processing chain hint stored in the asset references and effects the on-demand/scoped processing.
> 
> What happens in this scenario, does the asset get reprocessed from scratch and updated with a new processing chain hint?

Yeah, in this scenario, the asset will be reprocessed. For the processing chain hint, I think there're two situations:
- If developers hardcode the processing chain in code, the reference can be broken and they need to update the chain manually. It's similar to the case where an asset gets a new asset ID and developers has to replace any hardcoded asset ID in their code with the new one.
- For the processing chain hint that is serialized to disk, the asset serializer should be able to construct the new processing chain hint based on the database automatically when developers re-save the source file to disk. The processing chain hint is optional and mainly for the on-demand/scoped processing support, so it shouldn't break the actual asset reference even if it is out of date.

**Comment by monroegm** [comment]
This RFC is now in the final comment period. Please submit any remaining feedback by Tuesday, February 14.

**Comment by monroegm** [comment]
Approved on Thursday, February 16, 2023. @junbo75 Please submit to https://github.com/o3de/sig-content/tree/main/rfcs
