### ISSUE TITLE
Maintainer Request: Nicholas VanSickle

### ISSUE THREAD

**Issue by NicholasVanSickle** [o3de/sig-content#12]
I would like to nominate myself, @NicholasVanSickle, to become a maintainer on behalf of sig-content.

Per the maintainer requirements:
- Has been a Reviewer for 2+ months
    - I've been a Reviewer since O3DE became public on Github. Notably, I've authored a [single digit PR](https://github.com/o3de/o3de/pull/7).
- 8+ reviewed Pull Requests in the previous 2 months
    - I've reviewed [53 Pull Requests](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3ANicholasVanSickle+updated%3A2021-07-18..2021-09-16) in the preceding two months as of 2021-09-16
- 200+ lines of code changed across all reviewed Pull Requests
    - I'm unsure on how best to generate this metric, but I'll note this [single community PR](https://github.com/o3de/o3de/pull/2840) adds 838 lines of code (and removes an incredible 6237).
- 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
    - See below

**Comment by cgalvan** [comment]
I, as an O3DE Maintainer (can be verified here https://github.com/orgs/o3de/teams/maintainers/members) support this promotion

**Comment by bosnichd** [comment]
Fully support this!

**Comment by hultonha** [comment]
I also support this promotion (as an existing O3DE maintainer)

**Comment by alexmontAmazon** [comment]
I, as an O3DE Maintainer (can be verified here https://github.com/orgs/o3de/teams/maintainers/members) support this promotion

**Comment by monroegm** [comment]
Approved.
