### ISSUE TITLE
SIG-Content Nomination/Election

### ISSUE THREAD

**Issue by lsemp3d** [o3de/sig-content#127]
Current Chair: @lsemp3d  (discord: Luis Sempé [Amazon])
Current Co-Chair: @monroegm (discord: Gavin Monroe [Amazon])

Nomination Timeline: April 3rd, 2023 - April 14th, 2023 [NOMINATION PERIOD]
Election Timeline: April 17th, 2023 - April 21st, 2023 [ELECTION PERIOD]
Term begins: April 28th, 2023 [TERM BEGIN]

## SIG-Content Chair/ Co-Chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless distinctly required, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, the chair is considered to be an on-call position during this period. As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the SIG, the chair will be called to perform a responsibility.

## Responsibilities

The responsibilities of the SIG-Content group are detailed in the [SIG-Content Charter](https://github.com/o3de/sig-content/blob/main/governance/SIG%20Content%20Creation%20Charter.md)

## Nomination Process

Nomination may either be by an O3DE community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on [NOMINATION PERIOD].

## Nomination requirements
The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

## How to nominate
Nominations will be accepted for 2 weeks during the [NOMINATION PERIOD]
Nominate somebody (including yourself) by responding to this issue with:

A statement that the nominee should be nominated for a chair position in SIG-Core. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.

The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.

The GitHub username of the nominee (self-nominations need not include this; it's on your post.)

Nominee's Discord username (it is required to be an active Discord user if you are a chairperson.)

## Election Process

The election will be conducted from [ELECTION PERIOD] and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and SIG-Content may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current interim chair, they will announce the results in the Discord SIG channel as well as the SIG O3DE mailing list no later than [TERM BEGIN]. If there is no interim chair, the executive director will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on [TERM BEGIN]. Tentatively SIG chairs will be elected on a yearly basis.

## Other Links

SIG-Content Mailing List: https://lists.o3de.org/g/sig-content/topics
O3DE Calendar: https://lists.o3de.org/g/o3de-calendar/calendar

**Comment by aFinchy** [comment]
Hi @lsemp3d I pinged @Naomi-Wash on this election to help reach a further audience.

**Comment by lsemp3d** [comment]
Closing nominations as none were presented. I will remain as chair, @monroegm will step down as co-chair leaving the position vacant. Thank you @monroegm for all the work running meetings and triaging hundreds of issues!
