### ISSUE TITLE
Maintainer Promotion - @jonawals

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-content#13]
I would like to nominate @jonawals to be promoted from reviewer to maintainer status.

John meets all the requirements set out for becoming a maintainer except additional maintainer approval (more details here - https://github.com/o3de/community/blob/main/community-membership.md)

- Has been a Reviewer for 2+ months
- 8+ reviewed Pull Requests in the previous 2 months
- 200+ lines of code changed across all reviewed Pull Requests
- 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer

I'll look for additional support and can this then please be discussed in the next sig-content meeting.

Thanks!

**Comment by greerdv** [comment]
I'm happy to support this.

**Comment by moraaar** [comment]
Happy to support this.

**Comment by monroegm** [comment]
Approved
