### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by tkothadev** [o3de/sig-content#131]
### Nomination Guidelines
**Maintainer Nomination Requirements**
- [x] Has been a Reviewer for 2+ months -- became Reviewer back in November 2022
- [x] 8+ reviewed Pull Requests in the previous 2 months -- https://github.com/o3de/o3de/pulls?q=is%3Apr+reviewed-by%3Atkothadev
- [x] 200+ lines of code changed across all reviewed Pull Request
Current contributions as seen on the O3DE contributors page:
![image (19)](https://user-images.githubusercontent.com/112996779/228691049-29aebf8d-b03e-4d20-b2ba-04941ae04e3c.png)

* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: tkothadev to become a Maintainer on behalf of sig-content. I verify that I have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/tkothadev***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-alexpete** [comment]
I support the promotion of @tkothadev from Reviewer to Maintainer 🥳

**Comment by lsemp3d** [comment]
I also support @tkothadev to Maintainer!
