### ISSUE TITLE
Maintainer Request: AMZN-daimini

### ISSUE THREAD

**Issue by AMZN-daimini** [o3de/sig-content#14]
I would like to nominate myself, @AMZN-daimini , as a maintainer on behalf of sig-content.

Requirements:
- Has been a Reviewer for 2+ months
    My first PR was on April 15: https://github.com/o3de/o3de/pull/48

- 8+ reviewed Pull Requests in the previous 2 months
    I reviewed 60+ PRs in the last 2 months ([list](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3AAMZN-daimini+updated%3A2021-07-18..2021-09-17+))

- 200+ lines of code changed across all reviewed Pull Requests
    A couple of 100+ line changes from the list above:
    https://github.com/o3de/o3de/pull/3051
    https://github.com/o3de/o3de/pull/3081

- 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
    Coming soon :)

**Comment by cgalvan** [comment]
I, as an O3DE Maintainer (can be verified here https://github.com/orgs/o3de/teams/maintainers/members) support this promotion

**Comment by lsemp3d** [comment]
I, as an O3DE Maintainer (can be verified here https://github.com/orgs/o3de/teams/maintainers/members) support this promotion

**Comment by monroegm** [comment]
Approved.
