### ISSUE TITLE
SIG Reviewer Nomination: mddvisu

### ISSUE THREAD

**Issue by cgalvan** [o3de/sig-content#144]
### Nomination Guidelines
**Reviewer Nomination Requirements**
- [x]  6+ contributions successfully submitted to O3DE (9 PRs merged)
- [x]  100+ lines of code changed across all contributions submitted to O3DE
```
$ git log --shortstat --author "mddvisu" --since "3 months ago" --until "today" | grep "files changed" | awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "Files changed:", files, "Lines inserted:", inserted, "Lines deleted:", deleted}'
Files changed: 48 Lines inserted: 591 Lines deleted: 138
```
- [x] 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***mddvisu***, to become a ***Reviewer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/mddvisu***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lsemp3d** [comment]
I support this nomination!

**Comment by cgalvan** [comment]
Officially approved: https://github.com/orgs/o3de/teams/sig-content-reviewers?query=mddvisu
