### ISSUE TITLE
SIG Reviewer Self-Nomination: guillaume-haerinck

### ISSUE THREAD

**Issue by guillaume-haerinck** [o3de/sig-content#150]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* [x] 6+ contributions successfully submitted to O3DE
* [x] 100+ lines of code changed across all contributions submitted to O3DE

->I worked on various system such as [ScriptCanvas debugger](https://github.com/o3de/o3de/pull/17879), [LUA Editor](https://github.com/o3de/o3de/pull/17894), [documentation](https://github.com/o3de/o3de.org/pull/2552), [lumberyard to o3de pipeline](https://github.com/o3de/o3de.org/pull/2545). All code PR listed [here](https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Aguillaume-haerinck). I am also already reviewing code reviews, some examples [1](https://github.com/o3de/o3de/pull/18150), [2](https://github.com/o3de/o3de/pull/18091), [3](https://github.com/o3de/o3de/pull/17910)

* [x] 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate myself: ***guillaume-haerinck***, to become a ***Reviewer*** on behalf of ***sig-content***. I would need two existing reviewers to verify that I have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/guillaume-haerinck***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lsemp3d** [comment]
I support this nomination!

**Comment by spham-amzn** [comment]
I support this nomination!

**Comment by gadams3** [comment]
I support this nomination!

**Comment by lsemp3d** [comment]
This nomination meets all the requirements, I will move on to the next step @amzn-changml can you help me add @guillaume-haerinck to the O3DE organization so that I can make him a sig-content-reviewer?

**Comment by amzn-changml** [comment]
Done. @guillaume-haerinck has been invited to the @o3de/sig-content-reviewers team

**Comment by guillaume-haerinck** [comment]
And I just joined ! Thank you all, looking forward to make more contributions
