### ISSUE TITLE
Maintainer Nomination:  jjjoness

### ISSUE THREAD

**Issue by tjmichaels** [o3de/sig-content#16]
I would like to nominate: jjjoness, to become a Maintainer on behalf of sig-content. I verify that they have fulfilled the prerequisites for this role.

Nominee's GitHub Profile: https://github.com/jjjoness?tab=overview

Maintainers that support this nomination should comment in this issue

**Comment by hultonha** [comment]
I support this nomination for @jjjoness to become a maintainer

**Comment by monroegm** [comment]
Approved.
