### ISSUE TITLE
Maintainer Nomination:  sphrose

### ISSUE THREAD

**Issue by tjmichaels** [o3de/sig-content#17]
I would like to nominate: sphrose, to become a Maintainer on behalf of sig-content. I verify that they have fulfilled the prerequisites for this role.

Nominee's GitHub Profile: https://github.com/sphrose?tab=overview

Maintainers that support this nomination should comment in this issue

**Comment by hultonha** [comment]
I support this nomination for @sphrose to become a maintainer.

**Comment by monroegm** [comment]
Approved.
