### ISSUE TITLE
SIG Maintainer Nomination for @srikappa-amzn

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/sig-content#24]
### Maintainer Nomination

I would like to nominate myself, ***@srikappa-amzn***([Github Profile](https://github.com/srikappa-amzn)) , to become a ***Maintainer*** on behalf of ***sig-content***. I verify that I have fulfilled the prerequisites for this role as stated below:

* Has been a Reviewer for 2+ months
Have been a reviewer since O3DE started. My first PR was in [April](https://github.com/o3de/o3de/pull/72)
* 8+ reviewed Pull Requests in the previous 2 months
Reviewed [23 pull requests](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Asrikappa-amzn+updated%3A2021-08-18..2021-10-18+) in the 2 months ending on 10-18-2021
* 200+ lines of code changed across all reviewed Pull Requests
[Here's a PR](https://github.com/o3de/o3de/pull/3653/files) I reviewed that has 700+ lines changed 
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
Please see comments section
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month
Reviewed more than 4 pull requests in the last 3 months : [July 2021](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Asrikappa-amzn+updated%3A2021-07-01..2021-08-01+), [August 2021](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Asrikappa-amzn+updated%3A2021-08-01..2021-09-01+) and [September 2021](https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Asrikappa-amzn+updated%3A2021-09-01..2021-10-01+)

**Comment by AMZN-daimini** [comment]
I support this promotion 👍

**Comment by AMZN-mnaumov** [comment]
I support this as well
