### ISSUE TITLE
SIG-Content 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-content#27]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

-  Features
    - **Prefabs**
        - Prefab Focus Mode. Enhanced support for editing prefabs in the viewport. 
            - Prefabs are now displayed in the Outliner and Viewport as a single object, regardless of how many entities are nested under them. To make changes to the prefab, the user now needs to expand it via the "Edit Prefab" action (there are multiple ways to access the action: right click context menu item, double click, + shortcut, edit button in the Outliner). That will move the Editor's focus to the selected Prefab; when a Prefab is in focus, editing is limited to it. All other instances of the same prefab in the scene will receive the changes in real time. 
        https://github.com/o3de/o3de/issues/3445 (first part of https://github.com/o3de/o3de/issues/3446)
        - Added support to delete entities spawned at runtime via the Spawnables system. 
        https://github.com/o3de/o3de/pull/4154
        - Improved messaging for prefab save operations - when saving a prefab, the user is prompted to save the nested prefabs too. Also adds dialog for unsaved changes on all open prefabs when closing the Editor or switching to a different level. 
        https://github.com/o3de/o3de/pull/3440
        - Prefab patching now uses a best-effort mechanism, which allow levels to be loaded with errors. 
        https://github.com/o3de/o3de/pull/2110
    - **Terrain**
        - Experimental Terrain System with mesh, physics and macro material support.  This is in an optional Terrain Gem that is disabled by default.
        https://github.com/o3de/o3de/issues/1847
    - **Viewport**
        - Updates to how entity space is handled in the viewport.
        https://github.com/o3de/o3de/issues/3580
        - Updates to how selection works in the viewport. 
        https://github.com/o3de/o3de/issues/3578 
-  Bug fixes
    -  **Editor**
        - Resolved numerous Scaling/Dpi issues affecting environments with multiple screens with different dpi settings.
        https://github.com/o3de/o3de/issues/3339
    - **Prefabs**
        - Prefabs now store entity sort order information correctly.
        https://github.com/o3de/o3de/pull/5297
    - **Viewport**
        - Thickness of manipulator hit zones is configurable via a cvar.
        https://github.com/o3de/o3de/issues/3579
    - **Project Manager**
       - Better detection of whether a build fails when building through Project Manager
       - Link to view log while building
       - Showing the build button for projects that need to be rebuilt after a restart of Project Manager
       - Progress bars when deleting and cloning projects
       - Fix text being cut off incorrectly in multiple places in the Gem Catalog
       - Fixed lots of multiple of the same category appearing in the Gem Catalog
       - Fix some instances where building with Project Manager would take a long time with an install build
- Deprecations
- Known issues
    - Remote Desktop Camera Issues
        - If using the O3DE Editor over Remote Desktop (RD), controlling the camera using RMB to free-look can behave erratically. To avoid this, go to Edit -> Editor Settings -> Global Preferences, click on the Camera tab (on the left) and set Camera Capture Look Cursor to false. This will not hide the cursor when using RMB and will move the cursor while looking around. This will give much more consistent camera look behaviour. __Note: It is also useful to use this feature if using tablets or other pointing devices other than a mouse.__

**Comment by AMZN-alexpete** [comment]
**Project Manager**

Features

- Can now create a project-specific Editor desktop shortcut from each project's menu. (Windows only)
- Can open CMake-GUI from each project's menu and from the project's Build button, pre-filled with the paths for that project.
- Project Manager will now prompt to get and setup Python on start up if Python is not found.
- Engine Name, version and path now visible in Engine Settings.
- Gem Catalog shows notifications when Gems and their dependencies are added or removed.
- Gem Catalog shows Gem dependencies.
- Gem Catalog notifies you when removing a Gem will also remove Gem dependencies.
- Project path automatically updates based on project name text input field.
- External Gems can now be added from the Gem Catalog.
- Project Manager logs output to the .o3de/Logs folder.

Fixes

- Project Manager window cannot be resized on Mac and Linux.
- Project Manager window too large for screens under 800 pixels tall. [#3946](https://github.com/o3de/o3de/issues/3946)
- Project Manager window background transparent on Mac.
- "Edit Project Settings" menu does not support projects with spaces in the project path
- Cannot type in "Project Location" field.
- Crash when Python not found or misconfigured.
- Quantity of Gems showed is not automatically updated in Project Manager [#4074](https://github.com/o3de/o3de/issues/4074)
- Registered external Gems do not show up in Configure Gems when creating a project [#1965](https://github.com/o3de/o3de/issues/1965)

**Comment by AMZN-stankowi** [comment]
Asset Pipeline release notes:

- Fixed an issue where the Editor locks up when using bundle mode, after mounting a bundle that contains a legacy level https://github.com/o3de/o3de/pull/5625
- Fixed a failing asset bundler periodic test https://github.com/o3de/o3de/pull/5548
- Fixed all errors when using default seeds https://github.com/o3de/o3de/pull/5489
- Fixed asset bundles in release builds https://github.com/o3de/o3de/pull/5270
- Fixed a crash in the Asset Bundler GUI if you saved a bundle outside the default folder https://github.com/o3de/o3de/pull/5255
- Improved error reporting when a node has mixed skinned and unskinned meshes https://github.com/o3de/o3de/pull/3158
- Duplicate blend shape animations are now handled correctly, and fixed a crash with invalid animation targets https://github.com/o3de/o3de/pull/3080
- Updated how nodes are imported from AssImp into O3DE, and how poses are handled. Now all skinned meshes are imported with what Blender calls the "Rest Position" https://github.com/o3de/o3de/pull/2957
- Fixed an issue where sometimes scene processing would run the wrong python script on a processed scene file https://github.com/o3de/o3de/pull/2278
- Sped up sqlite BuilderGuid_Source_SourceDependency index https://github.com/o3de/o3de/pull/3648
- Asset bundler tests no longer time out https://github.com/o3de/o3de/pull/3356
- Fixed failing periodic Asset Pipeline tests that were timing out and using the wrong project path https://github.com/o3de/o3de/pull/2727

**Comment by amzn-mike** [comment]
- Restored lost fix - AP unresolved product dependency query failed to handle large number of products https://github.com/o3de/o3de/pull/2202
- Added xml output version of scene dbgsg files https://github.com/o3de/o3de/pull/3437
- Fixed AP handling of cache copy failure https://github.com/o3de/o3de/pull/1457
- Added early version of procedural prefab support https://github.com/o3de/o3de/pull/4481
- Fixed AP handling of absolute path wildcard dependencies https://github.com/o3de/o3de/pull/4574
- Fixed wildcard source dependencies not refreshing with new files https://github.com/o3de/o3de/pull/5054
- Fixed unit test leaking assert absorber https://github.com/o3de/o3de/pull/5176
- Fixed unit test leaking thread https://github.com/o3de/o3de/pull/5267
- Fixed AssetBus mutex not being re-locked before modifying the context again https://github.com/o3de/o3de/pull/5575
- Fixed race condition in asset loading https://github.com/o3de/o3de/pull/5604
- Fixed race condition in asset container loading https://github.com/o3de/o3de/pull/5721
