### ISSUE TITLE
Maintainer Request: Oscar Teng

### ISSUE THREAD

**Issue by chiyenteng** [o3de/sig-content#31]
I would like to nominate myself, @chiyenteng, to become a maintainer on behalf of sig-content.

Per the maintainer requirements:
- Has been a Reviewer for 2+ months
    - I've been a Reviewer at least 2 months. I've authored a PR around the beginning of this August: 
    https://github.com/o3de/o3de/pull/2715 .
    
- 8+ reviewed Pull Requests in the previous 2 months
    - I've reviewed 8 PRs this November: 
    https://github.com/o3de/o3de/pulls?q=is%3Apr+reviewed-by%3Achiyenteng+updated%3A2021-11-01..2021-11-30+
    
- 200+ lines of code changed across all reviewed Pull Requests
    - Around 200+ lines:
    https://github.com/o3de/o3de/pull/5389
    - From this PR I can see that I added/removed around 400 lines of code: 
    https://github.com/o3de/o3de/pull/2715
    
- 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
    - See below

**Comment by AMZN-AlexOteiza** [comment]
I, as an O3DE Maintainer (can be verified here https://github.com/orgs/o3de/teams/maintainers/members) support this promotion

**Comment by AMZN-daimini** [comment]
I support this promotion as well

**Comment by NicholasVanSickle** [comment]
I support this promotion!

**Comment by monroegm** [comment]
Approved at 12/2 SIG-Content meeting
