### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by michabr** [o3de/sig-content#34]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***michabr***, to become a ***Maintainer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/michabr***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by lsemp3d** [comment]
I support @michabr's nomination!

**Comment by cgalvan** [comment]
I second @michabr 's nomination!

**Comment by AMZN-koppersr** [comment]
I support @michabr 's nomination.

**Comment by AMZN-daimini** [comment]
I support this nomination too :)

**Comment by NicholasVanSickle** [comment]
And my axe! (gratuitous +1 from me)

**Comment by lsemp3d** [comment]
@monroegm Nomination was discussed and accepted during SIG-Content triage on 01/11/2022
