### ISSUE TITLE
SIG Reviewer Nomination

### ISSUE THREAD

**Issue by pollend** [o3de/sig-content#39]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***myself***, to become a ***Reviewer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***[https://github.com/pollend](https://github.com/pollend)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-daimini** [comment]
As a maintainer for sig-content, I support this promotion :)

**Comment by lsemp3d** [comment]
I also support @pollend's nomination

**Comment by lsemp3d** [comment]
Nomination was discussed and approved in monthly meeting on 1/27

**Comment by hultonha** [comment]
Sorry I missed this but great to hear @pollend's nomination went through! 😄 Congratulations!

**Comment by hultonha** [comment]
@lsemp3d did @pollend get added as a reviewer? I don't see them as part of the O3DE organization member. Do you have the power to add them? I'd like to propose @pollend become a maintainer as their continued contributions have been exemplary.

**Comment by amzn-changml** [comment]
@pollend has been invited to the org as part of the collaborator team. Once he's accepted the invite, @lsemp3d can add him as a member of the sig-content-reviewers team.

**Comment by AMZN-daimini** [comment]
As much as I agree in proposing pollend as a maintainer, I believe they may have been incorrectly added to the sig-content-maintainers group before the proposal was even written or accepted :)

**Comment by hultonha** [comment]
Yes I believe this was a mistake, @pollend should definitely have already been a reviewer, it just seems they weren't officially added, but I think they've now hopped directly to maintainer 😅 I was literally about to open a ticket about this, let me do it now to make it official (I am pretty certain they make the requirements anyway)

**Comment by hultonha** [comment]
Created maintainer nomination here - https://github.com/o3de/sig-content/issues/59

**Comment by lsemp3d** [comment]
Apologies, I was just very excited to see @pollend as a maintainer I skipped a step. Thanks @hultonha!
