### ISSUE TITLE
SIG Reviewer/Maintainer Nomination AMZN-nggieber 

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-content#41]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: AMZN-nggieber, to become a Maintainer on behalf of sig-content. I verify that they have fulfilled the prerequisites for this role. AMZN-nggieber has been a primary contributor to the O3DE Project Manager feature.

* Nominee's GitHub Profile https://github.com/AMZN-nggieber

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by hultonha** [comment]
As a maintainer of sig-content I approve of this nomination 👍

**Comment by AMZN-alexpete** [comment]
As a maintainer I approve this nomination.

**Comment by AMZN-Gene** [comment]
👍 I approve

**Comment by AMZN-Phil** [comment]
As a maintainer I approve this nomination

**Comment by monroegm** [comment]
Approved at SIG-Content Triage on February 8, 2022
