### ISSUE TITLE
SIG Maintainer Nomination - pollend

### ISSUE THREAD

**Issue by hultonha** [o3de/sig-content#59]
**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

### Maintainer Nomination

I would like to nominate: **[Pollend](https://github.com/pollend)**, to become a **Maintainer** on behalf of **sig-content**. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile **[Pollend](https://github.com/pollend)**

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by hultonha** [comment]
@pollend if you're able to add a list of your approved PRs and reviews that would be super helpful. Thank you!

**Comment by greerdv** [comment]
I support the nomination as a maintainer on sig-simulation, where pollend has made several valuable contributions.

**Comment by pollend** [comment]
here is a filter of the PR's that I have worked on: https://github.com/o3de/o3de/pulls?q=is%3Apr+author%3Apollend+is%3Aclosed

not sure about reviewed PR's though

**Comment by monroegm** [comment]
Congrats @pollend! Tis nomination was approved by SIG Content on June 8, 2022.

**Comment by pollend** [comment]
I accept this nomination and agree to fulfill the role as a maintainer for sig-content
