### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by gadams3** [o3de/sig-content#60]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: @gadams3, to become a Reviewer+Maintainer on behalf of @o3de/sig-content @o3de/sig-graphics-audio. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/gadams3

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by hultonha** [comment]
I 100% support this nomination as a member of sig-content 🙂

**Comment by AMZN-daimini** [comment]
> I would like to nominate: @gadams3, to become a Reviewer+Maintainer on behalf of https://github.com/orgs/o3de/teams/sig-content

How does this work? The Maintainer nomination has a requirement of at least 2 months as a Reviewer, so I don't think one can get both roles at once.

(I support the nomination either way, just confused by how this works)

**Comment by monroegm** [comment]
@gadams3 You are already a maintainer for SIG-Content
