### ISSUE TITLE
SIG Reviewer Nomination

### ISSUE THREAD

**Issue by amzn-tmryan** [o3de/sig-content#64]
### Reviewer Nomination for O3DE/sig-content

I would like to nominate: ***amzn-tmryan***, to become a ***Reviewer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/amzn-tmryan***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by NicholasVanSickle** [comment]
As a maintainer of sig-content, I support this nomination.

**Comment by amzn-tmryan** [comment]
This PR servers as proof of meeting the lines of code requirement: https://github.com/o3de/o3de/pull/10885/files

**Comment by AMZN-daimini** [comment]
As a maintainer of sig-content, I support this nomination.

**Comment by monroegm** [comment]
Congrats @amzn-tmryan! You are now a reviewer for SIG-Content. Your nomination was approved on August 4, 2022 at the SIG-Content Triage Meeting
