### ISSUE TITLE
SIG Reviewer Nomination

### ISSUE THREAD

**Issue by forkercat** [o3de/sig-content#74]
### Nomination Guidelines
**Reviewer Nomination Requirements**
- 6+ contributions successfully submitted to O3DE - [6 commits]
- 100+ lines of code changed across all contributions submitted to O3DE - [839 lines]
- 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
- Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate myself: ***forkercat***, to become a ***Reviewer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

- Nominee's GitHub Profile: https://github.com/forkercat

**Comment by srikappa-amzn** [comment]
I support this nomination.

**Comment by michabr** [comment]
I support this nomination!

**Comment by lsemp3d** [comment]
I also support this nomination!
