### ISSUE TITLE
RFC: Create SIG/Content working groups around areas of expertise

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-content#81]
### Summary:

This RFC proposes the creation of light-weight working groups (WG) withing SIG/Content where we have subject matter experts who are prepared to volunteer their time.

Based on a rough division of issues, as well as active SIG/Content members in the areas, this RFC suggests WG for:

* Editor
* Viewport
* Project Manager
* Assets (Asset Pipeline and Scene Pipeline)
* Scripting
* Prefabs

This list is not definitive and will be adjust as/when we have volunteers in a specific area.

### What is the motivation for this suggestion?

SIG/Content is a huge SIG, even after the split to SIG/Simulation the SIG still owns 44% of issues in O3DE. Individual contributors have stated they feel overwhelmed with the scope of the SIG and find it impossible to keep up with Discord conversations, issue triage etc as so much of it is not directly related to their areas of interest or expertise.

### Suggestion design description:

Its proposed we form lightweight working groups inside SIG/Content, such that each working group:

* Has a very clear ownership area in SIG/Content. Ownership should be called out in SIG/Content charter.
* Has a feature label aligned to the WG, to indicate significant area of ownership ie `feature/viewport`, `feature/asset-pipeline`
* Has an active membership, recommendation is to have at least three active members, where "active" is defined as engaged in some activity for WG in the last month)
* Has its own SIG thread/text channel “under” umbrella of SIG/Content.
* Has its own reviewers notifications list/team. Note: reviewers/maintainers must follow SIG/content reviewer and maintainer rules and be accepted by SIG.

Its proposed that we create a split in SIG/Content meetings and process such that working group will:

* Meet regularly to triage assigned issues (WG must have feature/x label in O3DE/O3DE project). Proposal is either weekly or bi-weekly depending on WG cadence.
    * WG should have some mechanism to regularly look at incoming issues to take load from main SIG/Content issue triage.
* Aids and assists any RFCs in area of ownership
* WG maintains their own sig-content-<working group>-reviewers and sig-content<working-group>-maintainers lists, members must meet bar for SIG/content reviewers and maintainers. It maybe that WG just has single list, depending on membership.
* WG is active and responsive to queries in working SIGtext chat area.
* WG members are active in general SIG/content discussions when related to areas of expertise.
* WG brings any cross SIG issues to SIG/content discussions asap.
* WG will report into general SIG/Content monthly meeting about activities (brief report with most important/impactful things). 

SIG/Content owns management of working groups and can at any time ask working group to disband if its not active or working effectively.

### What are the advantages of the suggestion?

Align SMEs around clear areas of ownership, break up the surface area of SIG/Content

### What are the disadvantages of the suggestion?

Risk of adding more process. SIG Chair(s) need to manage working groups and ensure they are in good standing.

### How will this be work within the O3DE project?

Will inform TSC and in SIG/Content Discord. SIG will set some measure for success and run working groups under an experimental banner until such time value can be identified or working groups disband due to lack of activity.

### Are there any alternatives to this suggestion?

We could split the SIG further but SIGs are heavyweight things (need charters, repros chairs with time etc). If a working group grows to a healthy size and has volunteers to run as SIG then working group can propose new SIG with TSC (following pattern of SIG/simulation formation as a guidance),

### What is the strategy for adoption?

1. Identify owners of working groups, ask owners for six month commitment. 
2. SIG/Content agrees formation of working groups and grants them scope. 
    1. SIG/Content adds any WG information to its README.md
    2. Advertise split to SIG/Content, sig-all and at TSC
3. Create Discord channel for working group plus reviewer notification list/team.
4. SIG will monitor working groups to ensure issue triage is occurring/working group is adding value or engaging more members.
5. Working group to send representative to SIG/content monthly meeting and raise issues of interest to SIG in general SIG chat.

## Open Questions / Thoughts

* How do we avoid adding too much extra process here? Want to avoid discouraging contributors.
* Proposal is written that SIG/Content does one "all SIG" triage once a week and routes issues to WGs, handles issues in areas without WG or high priority critical/blockers. WG meet regular to triage issues assigned to them. Unclear if this is the best approach and maybe something that has to be refined once WG are active.
* Should we update .codeowners file with new reviewer groups? Pro is that ownership is very clear, Con segmenting conversation around PRs in the SIG
* Unc;lear if WG needs to attend monthly SIG meeting (proposal is written that a representative will attend), but meeting could take written summary at a minimum from WG.

**Comment by Ulrick28** [comment]
I like the idea, but we will need to strike a balance on granularity. Too much granularty and the sig becomes just a collection of working groups for each feature. The overhead may not be worth the benefit.

**Comment by hultonha** [comment]
I am fully supportive of this. I'd be interested to see it start small and then build up, adding more working groups as we work out the kinks (rather than kicking off all working groups in one go) but other than that (a process detail) this makes total sense and is an awesome idea!

**Comment by monroegm** [comment]
At SIG-Content Triage on Wednesday, October 26, 2022, we decided to initiate the final comment period for this RFC. Please submit all remaining feedback by Monday, October 31, 2022.

**Comment by lmbr-pip** [comment]
Should add a note covering discovery. All WGs should have a folder in SIG/content with a README describing the WG does, when it meets. These would be linked to the general README

**Comment by monroegm** [comment]
Approved at SIG-Content Triage on Wednesday, November 2, 2022. Please commit this RFC to the [repo](https://github.com/o3de/sig-content/tree/main/rfcs).
