### ISSUE TITLE
Request to create a 'feature/asset-browser' issue label

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/sig-content#85]
Proposing SIG/content adds a feature/asset-browser label 

Label is useful because:
* It separates out a larger area of work, the asset-browser
* Issues in this area often get tagged either feature/asset-pipeline (asset browser is considered an editor feature) or feature/editor (broad)
* Contributors for asset-pipeline vs asset-browser tend to be distinct.

**Comment by AMZN-stankowi** [comment]
I like this, it would help me a lot with tickets I tend to work on.

**Comment by monroegm** [comment]
At SIG-Content Triage on Wednesday, October 26, 2022, we decided to initiate the final comment period for this RFC. Please submit all remaining feedback by Monday, October 31, 2022.

**Comment by monroegm** [comment]
Approved at SIG-Content Triage on Wednesday, November 2, 2022. Please commit this RFC to the [repo](https://github.com/o3de/sig-content/tree/main/rfcs).
