### ISSUE TITLE
Proposed RFC Feature Pseudo Random Number Generator for Script Canvas.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/sig-content#87]
### Summary:
O3DE as of right now does not have a way to get repeatable random numbers in script canvas. This is needed for many purposes, but one use case in particular that I am trying to create is procedural generation. If you look at many of the largest games that have procedural generation, it is not random every time you enter the game, and the game uses Pseudo Random Number Generators to generate the game. This is known by a seed value which users can usually put in before starting their game to have a repeatable instance of a game. More great information can be found on this page https://www.unitychain.io/blog/random-number-generation-and-their-use-cases/#:~:text=Number%20Generation%20(white)-,Pseudo%2DRandom%20Number%20Generators,-PRNGs%20seem%20random
### What is the relevance of this feature?
This feature is relevant because not only will it allow for repeatable seed based generation, it will also allow for other use cases not involving game development. This includes a large portion of simulation based projects use PRNG's, and some industrial use cases as well. More information on the industrial side of PRNG usage (https://arxiv.org/pdf/2007.11839.pdf).
### Feature design description:
The design of this feature would fully be node based in Script Canvas.
The nodes would look similar to the Random nodes in Script Canvas, but with addition of either a Seed value, or a Stream Value depending on how we would like to go about PRNG.

Example Use Case : You would be able to very simply open up Script Canvas, add an On Graph Start node, and from that node add the PRNG node which would have three input pins, the first would specify the min value, the second would specify the max value, and the third would specify the seed value. From that node we would go into a print node and run the project in runtime. As long as we have the same seed the console should always print the same value on each start, if we change the seed the value may/should change, and it should again repeat in the console on every run of the project until the seed is changed.

New Terminology ;
Stream : Another term for Seed
PRNG : Pseudo Random Number Generator
### Technical design description:
Inside of the node you start with having you Seed value which goes through a multiplier, next it goes through an increment. The Increment is the final part of stage 1, and than the increment is used in the modulus which takes your specified limits (Pin 1 and Pin 2 on the Node) into consideration before putting out an output. The output becomes the new seed and the process repeats.
This GIF should also help explain the process of PRNG ;
https://www.unitychain.io/blog/wp-content/uploads/2018/10/unitychain-PRNG-1.gif

Explain any API or process changes required to implement this feature
'I am not familiar with much of the API in O3DE, so I cannot safely say if any will have to be changed'

This feature should not have any problem on any platform or hardware.

### What are the advantages of the feature?
The advantages of this feature are that it is much quicker than real RNG generators, it is repeatable on each runtime test, and it has many use cases in all aspects of 3d engine work, not just game development.
### What are the disadvantages of the feature?
Some disadvantages of this feature would be script canvas math library would become slightly larger, and a new variable would possibly have to be introduced into script canvas.

### How will this be implemented or integrated into the O3DE environment?
The implementation of this feature would be done the same way other math nodes have been made inside of O3DE. (I am not too familiar with the process myself)
### Are there any alternatives to this feature?
There are no good alternatives to this feature, O3DE Script Canvas does not have PRNG support right now, and this is the most battle tested/used way of doing PRNG.

### How will users learn this feature?
Users can learn the feature by looking on a docs page that should be released after the development of this feature, stating what each pin does, and a possible simple use case of such nodes. The overall usability of such a feature can be figured out just by looking at the node in the viewport with the naming alone.

### Are there any open questions?

**Comment by ParasiteSt** [comment]
https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/Blueprints/UserGuide/RandomStreams/
This is Unreal's way of doing PRNG in Blueprints. I thought to share this as well as Streams is a slightly different way of going about this, but would need another variable introduced into O3DE, otherwise a number could easily be used as the seed.

**Comment by ParasiteSt** [comment]
Another note, I do have a completely working version made out of already available nodes in script canvas. I figured out how to make such a thing while doing my research for this RFC. So for me this RFC is sort of a take it or leave it, but having the nodes available to everyone in a compact form would help people that are trying to do PRNG that do not know the inner workings of it. This graph for example is honestly all you need to make a PRNG inside of Script Canvas with nodes already available;
![image](https://user-images.githubusercontent.com/100494538/197943783-1edf3eae-9bd8-4a4b-8e86-bcbe7d6ec5db.png)

**Comment by ParasiteSt** [comment]
Just curious if this RFC has gone through discussion? If so what was the final decision, should this RFC be closed, or is this something that may be looked into further to possibly be introduced into O3DE?

**Comment by monroegm** [comment]
This RFC is now in the final comment period. Please submit any remaining feedback by Tuesday, February 14.

**Comment by monroegm** [comment]
Approved on Thursday, February 16, 2023. @ParasiteSt Please submit to https://github.com/o3de/sig-content/tree/main/rfcs
