### ISSUE TITLE
SIG Maintainer Nomination - forkercat

### ISSUE THREAD

**Issue by forkercat** [o3de/sig-content#91]
### Nomination Guidelines

**Maintainer Nomination Requirements**
- [x] Has been a Reviewer for 2+ months - https://github.com/o3de/sig-content/issues/74
- [x] 8+ reviewed Pull Requests in the previous 2 months [Created 11 PRs and Reviewed 23 PRs since September]
- [x] 200+ lines of code changed across all reviewed Pull Request - [It should be 200+ lines]
- [x] 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
- [x] Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate myself: ***forkercat***, to become a ***Maintainer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***< https://github.com/forkercat >***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by michabr** [comment]
I support forkercat's promotion from Reviewer to Maintainer!

**Comment by AMZN-alexpete** [comment]
Congrats!
