### ISSUE TITLE
SIG Reviewer Nomination tkothadev

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/sig-content#92]
### Nomination Guidelines
**Reviewer Nomination Requirements**
- [x] 6+ contributions successfully submitted to O3DE (50+ contributions in last 2 months)
- [x] 100+ lines of code changed across all contributions submitted to O3DE 
```
git log --shortstat --author "tkothadev" --since "2 months ago" --until "today" | grep "files changed" | awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "Files changed:", files, "Lines inserted:", inserted, "Lines deleted:", deleted}'

Files changed: 100  Lines inserted: 2052 Lines deleted: 996
```
- [x] 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
- [x] Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month (12 PRs reviewed in last 2 months)

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***tkothadev***, to become a ***Reviewer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***< https://github.com/tkothadev >***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-Phil** [comment]
I second this nomination

**Comment by lmbr-pip** [comment]
IMHO you need @tkothadev to accept this nomination as well. They need to confirm in their own words that they are accepting the responsibility

**Comment by monroegm** [comment]
Congrats @tkothadev. The SIG chairs got together and confirmed your nomination. You should now be a reviewer. Thanks!
