### ISSUE TITLE
Proposed RFC Feature: Product Sub ID Type Update

### ISSUE THREAD

**Issue by junbo75** [o3de/sig-content#93]
### Summary:
In O3DE, each product asset is identified via a unique product asset ID. These asset IDs are comprised of the source asset GUID and the sub ID, an unsigned 32 bit number assigned by the Asset Builder that processed the source asset. However, these number sub IDs are opaque and convey little to note data to most users. Asset Builder authors/maintainers always find it hard to fix issues when an Asset Builder incorrectly generate sub IDs that collide for a given source asset or vary from run to run of the Asset Processor. Content creators have to spend time querying the asset database or checking additional tools like the Asset Processor to figure out the product asset identified by a specific sub ID.

To solve these problems, this RFC proposes migrating the sub ID to a semantically meaningful string representation.

### What is the relevance of this feature?
Sub IDs must be stable and mutually exclusive from run to run of the Asset Processor; each product assets should be assigned the same sub ID each time it's re-processed. Common problems observed with the current number sub ID generation include:
- Sub IDs can be generated based on the ordering of assets, where the order of inputs or outputs changes causing product assets to be assigned new different sub ids from run to run.
- Hashing based on some subset of data leading to [Sub ID collisions](https://github.com/o3de/o3de/issues/10720).
- Using timestamps, processing time or other variant data as part of the sub ID generation algorithm.

A second problem is that the opaque sub IDs convey no semantic meanings, which makes it difficult for content creators to work with hand editing/writing source assets or identifying information about the specific product asset quickly.

With the proposed solution, the Asset Builders can use sub-parts of models as string sub IDs (mesh0, lod2 etc.) which are already meaningfully unique names and invariant to the processing order in many cases.

#### Terminology:
- [Source Asset](https://www.o3de.org/docs/user-guide/assets/pipeline/source-assets/) - Files that contain unprocessed data that you want to consume in Open 3D Engine (O3DE) Editor or Launcher. Source assets can include: models, textures, animations, audio files and other content, typically authored in digital content creation (DCC) tools.
- Product Asset - The output of a series of Asset Pipeline conversion steps on a source asset to optimize or convert it for use in O3DE. For example, the source asset might be a FBX but the pipeline crunches, optimizes and converts it into an AtomMesh product asset. The engine loads the product asset only, not the original FBX.
- [Asset Builder](https://www.o3de.org/docs/user-guide/assets/pipeline/asset-builders/) - A process which handlers specific types of source assets and converts them to product assets.
- [Asset Bundler](https://www.o3de.org/docs/user-guide/packaging/asset-bundler/) - A tool for packaging specific product assets used for the release of O3DE applications.
- Source GUID - A source GUID is used to identify assets. It is generated by hashing the path-relative to the scan folder-of the source asset file. It is technically a UUID value, but is commonly referred to as a GUID.
- Sub ID - Sub Index of a product asset which distinguish it from other product assets produced from the same source asset. Sub IDs are usually generated by an asset builder. They must be stable for running in a build, and mutually exclusive. 
- Asset ID  - The asset ID consists of the source UUID plus a sub ID, which uniquely identifies a product.

#### High Level Design:
1. Update the sub ID inside the Asset ID structure from a 32 bit number to a unique name string.
2. Facilitate new mechanisms to submit a string sub ID for each product asset. The default behavior is to use the product asset file name (which has to be unique since it has to fit in the same folder as all the other product assets) as sub ID. 
3. The asset system will support both of the 32 bit number and string sub IDs side-by-side. The number sub ID will be converted to a string and written to the database for backward compatibility.
4. For existing source assets, A [version convertor](https://www.o3de.org/docs/user-guide/programming/components/reflection/serialization-context/versioning/#version-converters) will be implemented to convert the serialized legacy sub ID and store them in the new type when the data is serialized again (e.g. re-save the asset in O3DE tools).
5. A command line tool will be created for scanning and migrating the legacy sub IDs referenced in the existing source assets.

#### Example:
Consider a product asset "game.output" generated from the source asset "game.source" (Source GUID: {68458F51DA535183B342E7C9415026C3}).

Before this proposal:
- Asset ID of game.output is {68458F51DA535183B342E7C9415026C3} : 0
- Any reference to game.output in other source assets (e.g. prefab) will be saved as below when serialized to disk in the JSON format:
```
"Asset": {
    "assetId": {
        "guid": "{68458F51DA535183B342E7C9415026C3}",
        "subId": 0
    },
    "assetHint": "game.output"
}
```

After this proposal:
- Asset ID of game.output becomes: {68458F51DA535183B342E7C9415026C3} : game.stage2output
- Any reference to game.output in other source assets (e.g. prefab) will be saved as below when serialized to disk in the JSON format:
```
"Asset": {
    "assetId": {
        "guid": "{68458F51DA535183B342E7C9415026C3}",
        "subId": "game.output"
    },
    "assetHint": "game.output"
}
```

#### AzCore level
The existing [AssetId](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetCommon.h#L55) data structure will be updated to support the new sub ID type.
```
Before:
struct AssetId
{
    ...
    explicit AssetId(AZStd::string_view guidString, u32 subId = 0);
    AssetId(const Uuid& guid, u32 subId = 0);
    ...
    Uuid m_guid;
    u32 m_subId;
};
 
After:
struct AssetId
{
    ...
    //! O3DE_DEPRECATION_NOTICE(GHI-1234)
    //! Constructor for the legacy asset ID which consists of a source GUID and a number sub ID.
    //! The number sub ID will be converted to a string automatically.
    explicit AssetId(AZStd::string_view guidString, u32 subId = 0);
 
    //! O3DE_DEPRECATION_NOTICE(GHI-1234)
    //! Constructor for the legacy asset ID which consists of a source GUID and a number sub ID.
    //! The number sub ID will be converted to a string automatically.
    AssetId(const Uuid& guid, u32 subId = 0);
     
    explicit AssetId(AZStd::string_view guidString, const AZStd::string& subId);
    AssetId(const Uuid& guid, const AZStd::string& subId);
 
    ...
    Uuid m_guid;
    AZStd::string m_subId; //string type of sub ID.
};
```

Any legacy number sub ID passed to the AssetId structure will be converted to the string for backward compatibility. For example, legacy sub ID 0 will be saved as string "0" underneath. 

An [version convertor](https://www.o3de.org/docs/user-guide/programming/components/reflection/serialization-context/versioning/#version-converters) will be created to convert existing serialized sub IDs and save them in the new type when the source asset is saved to disk again. Meanwhile, the [AssetSerializer](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Asset/AssetSerializer.h#L34) will also be updated for converting the legacy sub IDs from any JSON formatted source assets.

#### AzToolsFramework level
On the tool side, any existing database entries, query functions or messages for interacting with the asset database (Check [AssetDatabaseConnection.h](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/AssetDatabase/AssetDatabaseConnection.h), [EditorAssetSystemAPI.h](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/API/EditorAssetSystemAPI.h) and [AssetProcessorMessages.h](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetProcessorMessages.h#L100)) require to be updated for using the new sub ID type. Asset system APIs that accept sub ID as an input will be updated as well to handle the string type sub ID. For example,
```
Before:
class ProductDatabaseEntry
{
public:
    ProductDatabaseEntry(AZ::s64 productID, AZ::s64 jobPK, AZ::u32 subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
    ProductDatabaseEntry(AZ::s64 jobPK, AZ::u32 subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
    ...
    AZ::u32 m_subID = 0;
    ...
};
 
bool QueryProductDependencyBySourceGuidSubId(AZ::Uuid guid, AZ::u32 subId, const AZStd::string& platform, productDependencyHandler handler);
 
After:
class ProductDatabaseEntry
{
public:
    //! O3DE_DEPRECATION_NOTICE(GHI-1234)
    //! Constructor for the product database entry with the legacy asset ID format.
    //! The number sub ID will be converted to a string automatically.
    ProductDatabaseEntry(AZ::s64 productID, AZ::s64 jobPK, AZ::u32 subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
 
    //! O3DE_DEPRECATION_NOTICE(GHI-1234)
    //! Constructor for the product database entry with the legacy asset ID format.
    //! The number sub ID will be converted to a string automatically.
    ProductDatabaseEntry(AZ::s64 jobPK, AZ::u32 subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
 
    ProductDatabaseEntry(AZ::s64 productID, AZ::s64 jobPK, const AZStd::string& subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
 
    ProductDatabaseEntry(AZ::s64 jobPK, const AZStd::string& subID, const char* productName,
        AZ::Data::AssetType assetType, AZ::Uuid legacyGuid = AZ::Uuid::CreateNull(), AZ::u64 hash = 0, AZStd::bitset<64> flags = 0);
    ...
    AZStd::string m_subID; // String type sub ID.
    ...
};
 
//! O3DE_DEPRECATION_NOTICE(GHI-1234)
//! Query the product dependencies via the source GUID and legacy number sub ID.
//! The number sub ID will be converted to a string automatically.
bool QueryProductDependencyBySourceGuidSubId(AZ::Uuid guid, AZ::u32 subId, const AZStd::string& platform, productDependencyHandler handler);
 
//! Query the product dependencies via the source GUID and string sub ID
bool QueryProductDependencyBySourceGuidSubId(AZ::Uuid guid, const AZStd::string& subId, const AZStd::string& platform, productDependencyHandler handler);
```

Schema of the following asset database tables will be modified accordingly to save the string type sub ID:
- LegacySubIDs
- MissingProductDependencies
- ProductDependencies
- Products
- SourceDependencies

##### Asset builder
Data structures that are defined in AssetBuilderSDK and use the 32 bit number sub ID will be updated to store the new string sub ID. For example,
- [JobDependency](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h#L379) - Its member variable m_productSubIds will be changed from a vector of u32 numbers to a vector of strings.
- [JobProduct](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/AssetBuilderSDK/AssetBuilderSDK/AssetBuilderSDK.h#L656) - Its member variable m_productSubID will be changed from a u32 number to a string. The member variable m_legacySubIDs will also become a vector of strings.

The Asset Builder will emit a unique string for each product asset inside the ProcessJob function and the product asset file name will be used as the default value. The old u32 sub ID will be saved as a legacy sub ID for backward compatibility. For example,
```
Before:
void AtlasBuilderWorker::ProcessJob(const AssetBuilderSDK::ProcessJobRequest& request,
        AssetBuilderSDK::ProcessJobResponse& response)
{
    ...
    response.m_outputProducts.push_back(AssetBuilderSDK::JobProduct(outputPath));
    response.m_outputProducts[static_cast<int>(Product::TexatlasidxProduct)].m_productAssetType = azrtti_typeid<TextureAtlasNamespace::TextureAtlasAsset>();
    response.m_outputProducts[static_cast<int>(Product::TexatlasidxProduct)].m_productSubID = 0;
    ...
}
 
After:
void AtlasBuilderWorker::ProcessJob(const AssetBuilderSDK::ProcessJobRequest& request,
        AssetBuilderSDK::ProcessJobResponse& response)
{
    ...
    response.m_outputProducts.push_back(AssetBuilderSDK::JobProduct(outputPath));
    response.m_outputProducts[static_cast<int>(Product::TexatlasidxProduct)].m_productAssetType = azrtti_typeid<TextureAtlasNamespace::TextureAtlasAsset>();
    response.m_outputProducts[static_cast<int>(Product::TexatlasidxProduct)].m_productSubID = "TexatlasidxProduct"
    response.m_outputProducts[static_cast<int>(Product::TexatlasidxProduct)].m_legacySubIDs.emplace_back("0");
    ...
}
```

##### Asset processor
After processing each new/modified source asset, the Asset Processor will write the string sub ID to the database and store the product asset's legacy number sub ID as a string into the LegacySubIDs table from the asset database.

The Asset Processor already includes an legacy asset ID system, which keeps a map of [legacy asset ID] -> [actual asset ID] that the system consults if it's asked for an asset and cannot find it. This legacy asset ID system will be revisited to make sure that any references to the legacy sub ID will be routed to the new sub ID correctly.

The updated string sub ID will be reflected directly in the Asset Processor GUI: When users select a product asset from the Assets tab, they will find the string sub ID included in the asset ID as below. When the string sub ID becomes too long, the asset ID will be truncated and the full text will be shown in a tooltip.
![image](https://user-images.githubusercontent.com/68558268/204596736-9e2bb1f9-22eb-4122-b34b-a55fca15b722.png)

##### Asset bundler
The Asset Bundler requires some logic updates for handling the new sub ID type. For example, the [AssetSeedManager](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Asset/AssetSeedManager.cpp#L54) will be updated for converting the new format of asset ID (Source GUID + string sub ID) to a string.

##### Command line tool for migration
A command line tool will be created to scan source assets inside the specified scan folders and replace legacy sub IDs. The tool will be built based on AzToolsFramework and take advantage of the asset system APIs to resolve the number sub IDs to strings and re-save the source assets to disk.

### What are the advantages of the feature?
- The string sub ID helps to improve the readability of sub ID and reduce the chance of collision caused by the hashing algorithm for generating u32 numbers. 
- Asset builders will less likely run into the broken reference or sub ID collision caused by the opaque number sub IDs.
- The sub ID will become more readable and meaningful for customers who need to create/edit source assets manually.

### What are the disadvantages of the feature?
- String sub ID may include sensitive asset information and has a larger size compared to the u32 number. Developers may want to strip the asset information out of the asset catalog and update the references before shipping their games/applications to the end users on consideration of the runtime catalog size and security.
- Updating the product asset names will cause the asset to be reprocessed and the default sub ID will change accordingly, which can break the existing references. The Asset Builder can specify custom strings as sub ID to mitigate this risk.
- Modifying the string sub ID of a product asset (e.g. new naming schema, legal/branding concerns, etc.) will cause the source assets to be reprocessed and break the existing references.
- This is an quite impactful change that touches the core of the asset system. It requires comprehensive testing on the asset processing pipeline as well as any systems that relies on the existing sub ID type.
- There're potential performance considerations on comparing or copying string sub IDs, but we don't expect really measurable impact because of this proposal. We can create some automated tests around performance when using asset IDs, and verify before / after this update. There are also very low-hanging fruits/mechanisms for solving it if performance actually becomes an issue: For example, string sub IDs can be read into [AZ::Name](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Name/Name.h#L74) on deserialization for fast comparisons, and written back to disk as plain strings via the custom asset serializer for readability. 

### How will this be implemented or integrated into the O3DE environment?
- The legacy number sub ID will be treated as a string and supported by the asset system for backward compatibility.
- Version converter and the updated asset serializer will help to convert the legacy sub ID to the new type when re-save the source asset via O3DE content tools.
- An O3DE tool (standalone executable or a tool integrated into AP) will be provided for migrating the legacy sub ID found in the existing source assets using the asset database information.

### Are there any alternatives to this feature?
- Update the individual Asset Builder to produce less product assets from a singe source asset or replace the hash algorithm for generating u32 numbers.
    - This may fix the sub ID collision issue in a specific system but cannot resolve it in the long term: The number sub ID is still confusing and opaque to developers, and the future system may produce large numbers of product assets from a source asset on purpose.
- Drop builder-authored sub IDs, and instead moved to a system where the sub ID generation was automatic (e.g. using relative path as sub ID, caching set of consumed sub IDs).
    - Asset information that AP knows about is quite limited and a few other facts (like asset relocation) can also influence the sub ID value. It could be hard to come up with a common mechanism that can be used to generate unique sub ID for all the asset types.

### How will users learn this feature?
- Customers will see warning messages in the console/log when calling deprecated APIs that only work with the legacy number sub ID with instructions for migration.
- Impactful change notification will be sent to the discord channel and included in the O3DE release notes.
- Public O3DE document will be updated for the new sub ID type and also notify developers about the deprecation.

### Are there any open questions?
- How will these changes work with the ongoing [RFC - Metadata Asset Relocation](https://wiki.agscollab.com/pages/createpage.action?spaceKey=~junbo&title=RFC+-+Metadata+Asset+Relocation)?
    - For the case where product asset file names don't change after the relocation (e.g. Developers move "shapes.fbx" around or rename it to othershapes.fbx, but if the FBX file contained cube, it would still output sub ID of cube), the sub ID change won't affect the asset relocation.
    - For the case where product asset file names are related to the source asset and will change after the relocation (e.g. Developers rename a script canvas file and the product asset names change accordingly), the asset builder is expected to override the default value and assign a custom sub ID (in the string format) based on its own requirements. AP or the asset builder may also take some mechanisms like including a special substring maker in the sub ID that represents the source asset name to work around this problem.

**Comment by Ulrick28** [comment]
Hi! Overall I am happy with this approached. However, I am a little concerned with this statement "There is a potential performance impact by changing the sub ID from the u32 number to string. We can **probably** mitigate it by creating some automated tests around performance when using asset IDs, and verify before / after this update. 

The word 'Probably' indicates that perf impact hasn't really been thought through for this change.

**Comment by VickyAtAZ** [comment]
Compare or copy a string can impact performance since we use AssetId in many places. This is a very big concern to me.
I wonder if the the main issue this RFC is trying to address is mainly an issue with build fbx file? Do you know other assets which may have the same issue. 
I prefer the alternative solution one. We can switch u32 to u64 to avoid collision if necessary. And we may come up with document to suggest how to generate sub id to developers.

**Comment by jeremyong-az** [comment]
For what it's worth, I don't believe I've ever seen a guid/small-string comparison show up in any runtime profile. Usually, the death-by-a-thousand cuts sorts of issues crop up more when we do things like lots of little allocations or similar. Using hashed strings (spelled `AZ::Name`) in our codebase also provides a way to do fast string equality rejection without doing a full comparison (which will be so fast as to be unnoticeable in most cases since `memcmp` is a pretty well optimized/vectorized routine in the CRT at this point)

**Comment by junbo75** [comment]
> I wonder if the the main issue this RFC is trying to address is mainly an issue with build fbx file?
People have reported sub ID collision issues with FBX and OBJ files currently (https://github.com/o3de/o3de/issues/10720, https://github.com/o3de/o3de/issues/9659 and https://github.com/o3de/o3de/issues/12606) and it's part of the reason for updating the sub ID type. We've also seen that builder authors misconfigured the sub ID, which caused broken references when the process order or other variant data changed. Content creators who hand edits/writes source assets complains about the confusing asset IDs as well since the asset IDs are not meaningful.

**Comment by junbo75** [comment]
> Using hashed strings (spelled AZ::Name) in our codebase also provides a way to do fast string equality rejection without doing a full comparison.

Yeah, sounds like AZ::Name could be a better option on consideration of performance. I'm not quite sure how it looks like when serialize AZ::Name to disk and one of the purpose for using a string is to improve the readability of asset ID/sub ID, but I'll look more into this type.

**Comment by AMZN-puvvadar** [comment]
> > Using hashed strings (spelled AZ::Name) in our codebase also provides a way to do fast string equality rejection without doing a full comparison.
> 
> Yeah, sounds like AZ::Name could be a better option on consideration of performance. I'm not quite sure how it looks like when serialize AZ::Name to disk and one of the purpose for using a string is to improve the readability of asset ID/sub ID, but I'll look more into this type.

This sounds like a good place to start. I echo @Ulrick28 's concern that it doesn't sound like there's been preliminary investigation into perf. I think if that's squared away, this will be in very good shape.

**Comment by AMZN-Gene** [comment]
> > Using hashed strings (spelled AZ::Name) in our codebase also provides a way to do fast string equality rejection without doing a full comparison.
> 
> Yeah, sounds like AZ::Name could be a better option on consideration of performance. I'm not quite sure how it looks like when serialize AZ::Name to disk and one of the purpose for using a string is to improve the readability of asset ID/sub ID, but I'll look more into this type.

Is having a human readable name on disk important? In each of the GHIs the subid that artists are seeing are in AssetProcessor warnings (they aren’t opening up and viewing files on disk by hand) so even if an az::name is serialized as 64bit hash on disk there might to be a way to convert back to display the human readable string when printing the error in AssetProcessor?

**Comment by junbo75** [comment]
> Is having a human readable name on disk important?
Yeah, readability is one of the problem we want to address with this sub ID change. However, the main use case is for creating/editing source files (e.g. ATOM related sources in the JSON format) which include reference to other assets manually. If az::name is serialized as 64bit hash, we may need to resolve it to a string somehow. Otherwise it may not help to improve the readability.

**Comment by junbo75** [comment]
I'm currently looking into the potential performance impact from this change. Talked with @AMZN-stankowi and the plan is as below:
1. We define a few performance tests to run, these can be semi-automated right now because we just want to gather a baseline. We'll worry about building the more robust Jenkins based automation later.
2. Run those tests, get the baseline. 
3. How much work would it be to, as a prototype, try swapping the existing sub ID to a string but continue to use numbers, just convert to string / from string as necessary? If this is like 2 days of work or less, then maybe we do that as an initial estimate of performance?
4. Re-run the tests after performing 3, to get a rough idea of what the performance cost will be.
5. Based on timing, we could also build a document that covers systems that will be impacted. Where and when sub IDs are used, so we could evaluate the document, to try to understand the specifics of the risk, instead of the current vague performance risk.

**Comment by AMZN-Gene** [comment]
> 

Ahh, so some ATOM source assets are JSON files that people need to write by hand that reference asset products with sub-ids? Yeah, in that case it would help if those product assets had human readable file names.

**Comment by junbo75** [comment]
> Ahh, so some ATOM source assets are JSON files that people need to write by hand that reference asset products with sub-ids? Yeah, in that case it would help if those product assets had human readable file names.

Users who are working with hand-edited/hand-written files complain about the UUID format. For example,
- When writing a shader file, or a resource group file, people usually edit the shader by hand. It's one thing if its something like “shapes.fbx:cube03.azmodel”, but they may get significant pushback if it's actually “{21873612873612876312312312} : 21312312".
- If developers are making a python script which generates a prefab - it's not ‘by hand’ but they don't want to deal with crazy UUIDs as well.

Atom provides JSON file types like shaders, materials, material types, passes, that should be considered “source files”. Even with proper tooling, these things need to be human readable and editable, able to be produced from script or tools that may have no connection to or knowledge of the AP.

**Comment by lawsonamzn** [comment]
We also don't have to serialize or use an AZ::Name on disk, we can read a string into an AZ::Name on deserialize, and write it back to string in the case of the custom asset serializer when written.
The result would be plain strings on disk and AZ::Name in memory for comparisons.  There is also opportunity to write it as 64bit or other hashed value for release builds if we want to go that far.

**Comment by jeremyong-az** [comment]
Yea I suppose the point is that I don't think performance is really a concern for this RFC because there are very low-hanging fruits/mechanisms for solving that if it actually becomes an issue. The underlying problem as described (sub-id stability, general correctness in the asset pipeline) feels more critical.

**Comment by junbo75** [comment]
I'm currently working on a prototype for comparing the performance impact of this sub ID change. Basically I just convert all the u32 number to a string directly for the testing purpose. I also created a test that assigns a model asset ID to the mesh component for 100K times (https://github.com/o3de/o3de/pull/13516). By comparing the time it took to run this specific test, there's no obvious difference between the u32 type and string type sub ID.

Based on the conversation above, there's likely no measurable impact on comparing the proposed type of asset ID/sub ID and we have very low-hanging fruits/mechanisms to address it if performance becomes a real problem after this change.

I'll update this RFC to call out the potential performance risk and our mitigation for it.

**Comment by junbo75** [comment]
I tried to run the benchmark tests from the [Atom Sample Viewer](https://github.com/o3de/o3de-atom-sampleviewer) project since Atom uses Asset ID in many places, and did more comparison based on the log timestamp. It took 3min 23sec to finish when using u32 sub ID vs 3min 30sec after switching to string sub ID.

**Comment by monroegm** [comment]
This RFC is now in the final comment period. Please submit any remaining feedback by Tuesday, February 14.

**Comment by monroegm** [comment]
Approved on Thursday, February 16, 2023. @junbo75 Please submit to https://github.com/o3de/sig-content/tree/main/rfcs
