### ISSUE TITLE
SIG Reviewer/Maintainer Nomination

### ISSUE THREAD

**Issue by dtamkin1** [o3de/sig-content#97]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***dtamkin1***, to become a ***Maintainer*** on behalf of ***sig-content***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***https://github.com/dtamkin1***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by cgalvan** [comment]
I support this nomination!

**Comment by AMZN-daimini** [comment]
As a sig-content maintainer, I support this nomination.

I have verified the requirements:
- PR reviewed by dtamkin1: https://github.com/o3de/o3de/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Adtamkin1
- I could not find the date of the approval as a reviewer, but I believe it has been more than 2 months.

**Comment by amzn-leenguy** [comment]
I support this nomination.

**Comment by monroegm** [comment]
Approved at SIG-Content Triage on December 7, 2022.

**Comment by Ulrick28** [comment]
I have added dtamkin1 to the maintainers list
